// src/app/layout.jsx
// Ini adalah root layout aplikasi Anda
export const dynamic = "force-dynamic"
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Portofolio Zulfian Hamzah",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children} {/* children di sini akan menjadi src/app/[locale]/layout.jsx */}
      </body>
    </html>
  );
}